### ISSUE TITLE
Embedded Chart Designer not invoking callback functions.

### ISSUE THREAD

**Issue by combisloic** [seatsio/seatsio-angular#2]
Hi, 

I have embedded a chart designer in my angular app. The designer appears correctly and let me create a chart. However the callback functions seem not to be invoked.

Here is my HTML : 
` <si-seatsio-designer designerKey="{{user.seatsIOCredentials.designerKey}}"
          (onChartCreated)="onChartCreated($event)"
          (openDraftDrawing)="openDraftDrawing($event)"
          (onChartUpdated)="onChartUpdated($event)"
          (onChartPublished)="onChartPublished($event)"
          (onExitRequested)="onExitRequested($event)"
          (openLatestDrawing)="openLatestDrawing($event)"></si-seatsio-designer> `

Here are the functions in my component : 

`
onChartCreated($event){
    console.log("created", $event);
}
`
`
openDraftDrawing($event){
    console.log("openDraft", $event)
}
`
`
onChartUpdated($event) {
    console.log("updated", $event);
  }
`
 `
onChartPublished($event) {
    console.log("published", $event);
}
`
`
onExitRequested($event){
    console.log("exit", $event);
  }
`
`
  openLatestDrawing($event){
    console.log("latest",$event);
  }
`

I don't know if it's related but I have a 404 not found error as well when loading the designer : 
https://cdn.seatsio.net/static/version/v325/chart-designer-v2/lodash.min.js.map

Thanks for your help !  :)

**Comment by mroloux** [comment]
Hi Loïc, you're right: for now those callbacks are not invoked. We'll put that on our TODO list.

**Comment by nahue** [comment]
@combisloic please try upgrading this library to `v6` .. and make sure you update your <si-seatsio-designer> invocation..

should be something like 
```html
<si-seatsio-designer [config]="config"></si-seatsio-designer>
```

and that `config` must be on your component , for example:

```js
  config = {
    designerKey: "<yourKey>",
    onExitRequested: () => console.log("Exit Requested"),
    onChartCreated: key => console.log("Chart Created", key)
  }

```

Please let us know if that works for you

**Comment by combisloic** [comment]
I upgraded to v6 and obtained another error : 
Error: Uncaught (in promise): TypeError: null is not an object (evaluating 'this.container().appendChild') createLoadingDiv@https://cdn.seatsio.net/chart.js:5:8174 render@https://cdn.seatsio.net/chart.js:5:26724 

The chart designer is not showing up at all.

Here is my chart designer component :
```html
<si-seatsio-designer [config]="config"></si-seatsio-designer> 
```
Here is my config object : 

```javascript
config = {

        designerKey : "<designerKey>",

        onChartCreated : (key) => {
          console.log(key);
        },

        onExitRequested : () => {
          console.log("exit")
        },

      }
```

I tried to had a `divId : "chart" ` field as well, but the error remains.

**Comment by nahue** [comment]
Sorry for the delay. I will be working on this today, will keep you posted!

**Comment by nahue** [comment]
Please try with v7 (we've fixed how the library handles divId)

**Comment by combisloic** [comment]
The issue remains when updating to v7.

**Comment by nahue** [comment]
Can you please share your project? or build a test project that i can try? I'm not sure how to reproduce this bug.

**Comment by combisloic** [comment]
Sorry, the last issue was my bad. 
The designer was embedded in a material MatTabCompent. 
Once removed everything work as expected.

thank you !
