### ISSUE TITLE
Angular v16 Ivy compatibility 

### ISSUE THREAD

**Issue by JoaoPauloLisboa** [seatsio/seatsio-angular#20]
Hi, 

To update my app to new angular version, I have an error related to seatsio that's blocking me.

_This likely means that the library (@seatsio/seatsio-angular) which declares SeatsioAngularModule is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy._

Is there a forecast to support angular v16?

**Comment by mroloux** [comment]
Oh yes of course, [v12](https://github.com/seatsio/seatsio-angular/releases/tag/v12.0.0) now supports Angular 16.
